name: Keep Supabase Active

on:
  schedule:
    - cron: '0 12 * * 1'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase Database
        env:
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: curl -X GET "https://wjrdjfiuvffbqseeflvr.supabase.co/rest/v1/reservations?limit=1" -H "apikey: $SUPABASE_KEY" -H "Authorization: Bearer $SUPABASE_KEY"